### ISSUE TITLE
Bug report: Out of memory

### ISSUE THREAD

**Issue by M-Gonzalo** [rrrlasse/eXdupe#6]
`eXdupe: Out of memory. This differential backup requires 1536 MB. Try -t1 flag`

I'm getting this, but I have plenty of free memory, about 10x what the message says I need.

Up until the last version this wasn't happening. Same command, same testbed. It started failing on dev13 Linux

**Comment by rrrlasse** [comment]
Sorry for the late reply.

Did you use the exact same dev-version for the full backup and the differential backup? Because the dev-versions are not always compatible (maybe I should state that in the README.md). If so, it might attempt to allocate a random amount of memory, and not just the 1536 MB.

Also, do you still see the problem with the latest version (15)?

**Comment by M-Gonzalo** [comment]
I don't remember exactly, but I believe so. I tried to add differentially to an older full backup. I'll run some tests later on a fresh sample
